Web6.0/mysite/blog/urls.py
from django.urls import path
from . import views 
#from .views import PostListView, PostDetaiViewl, post_share

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<uuid:post_id>/share/', views.post_share, name='post_share'),
    path('search/', views.post_search, name='post_search'),
]

Web6.0/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

Web6.0/mysite/blog/models.py
import uuid
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class AllPostManager(models.Manager):
    def get_queryset(self):
        return super(AllPostManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = AllPostManager() 
    

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title 

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

Web6.0/mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    from_email = forms.EmailField()
    #to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

Web6.0/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail



##implmenting function-based views
def post_list(request):
    posts = Post.published.all()
    paginator = Paginator(posts, 3) #delivering 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #if the page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts':posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

    #display list of active comments
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})

def post_share(request, post_id):
    #retrive the post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    #check if the request is a post method
    if request.method == 'POST':
        #if so, we send the form using  post request
        form = EmailPostForm(request.POST)


        #form validation
        if form.is_valid():
            cd = form.cleaned_data

            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'moroabdul@outlook.com', ['moroabdul@outlook.com'], fail_silently=False,)

        sent = True

    #if not, we instantiate a new form
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})



def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
           #
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query) 
            results = Post.published.annotate(
                search=search_vector, 
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

Web6.0/mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
 <div id="content">
 {% block content %}
 {% endblock %}
 </div>
 <div id="sidebar">
 <h2>My blog</h2>
 <p>This is my blog. I've written {% post_total %} posts so far.</p>
 <p>
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}
 </p>
 <p>
     <h3>Most commented posts</h3>
     {% show_most_comments 3 %}
 </p>
 </div>
</body>
</html>

Web6.0/mysite/blog/templates/blog/post/detail.html
<!-- templates/books/book_list.html -->
{% extends 'blog/base.html' %}
{% block title %} {{post.tite}}{% endblock title %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}
<p>
  <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
</p>
{% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment {{ total_comments|pluralize}}
  </h2>
{% endwith %}
{% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks}}
  </div>
{% empty %}
<p> There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
  <h2>Your comment has been added. </h2>
{% else %}
  <h2>Add a new comment</h2>
  <form method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
  </form>
{% endif %}
{% endblock content %}

Web6.0/mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_post %}
       <li>
           <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
       </li> 
    {% endfor %}   
</ul>
 

Web6.0/mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title  %} My Blog {% endblock title %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}
            </a>
        </h2>
        <p class="data">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body | truncatewords:30 | linebreaks}}
    {% endfor %}
        

    {% include 'pagination.html' with page=posts %}
{% endblock content%}

Web6.0/mysite/blog/templates/blog/post/most_comments.html
<ul>
 {% for post in most_comments %}
 <li>
 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 </li>
 {% endfor %}
</ul>

Web6.0/mysite/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %} Search {% endblock %}

{% block content %}
    {% if query%}
        <h1>Posts containing " {{ query }}</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
             {{ post.body|markdown|truncatewords_html:5 }}
             {% empty %}
             <p>There are no results for your query.</p>
        {% endfor %}
             <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
             <h1>Search for posts</h1>
             <form method="get">
             {{ form.as_p }}
             <input type="submit" value="Search">
             </form>
    {% endif %}
{% endblock %}
            

Web6.0/mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %} Share a post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent </h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif%}
{% endblock %}